apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-quota
  namespace: quota-lab
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 512Mi
    limits.cpu: "2"
    limits.memory: 1Gi
    pods: "3"