apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  namespace: project1
spec:
  replicas: 1
  stategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php
        image: php-crud-app:v1
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: php-config
              key: MYSQL_HOST
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: php-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: php-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"